config/routes.rb
Rails.application.routes.draw do

get 'sessions/new' => 'sessions#new', as: :new_sessions

delete 'sessions' => 'sessions#destroy', as: :session

post 'sessions' => 'sessions#create'

resources :photos
root 'events#index' 

get 'users/' => 'users#index', as: :users

get 'users/new' => 'users#new', as: :new_user

get 'users/:id' => 'users#show', as: :user

post 'users/' => 'users#create'

get 'users/:id/edit' => 'users#edit', as: :edit_user

patch 'users/:id' => 'users#update'

delete 'users/:id' => 'users#destroy'

get 'events/' => 'events#index'

get 'events/new' => 'events#new', as: :new_event

get 'events/:id' => 'events#show', as: :event

post 'events/' => 'events#create'

get 'events/:id/edit' => 'events#edit', as: :edit_event

patch 'events/:id' => 'events#update'

delete 'events/:id' => 'events#destroy'

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Geocoder::Model::Mongoid
geocoded_by :full_address               # can also be an IP address
after_validation :geocode       # auto-fetch coordinates    # auto-fetch coordinates

  
  field :title, type: String
  field :date, type: String
  field :time, type: String
  field :full_address, type: String
  field :address, type: String
  field :city, type: String
  field :state, type: String
  field :zip, type: Integer
  field :desc, type: String
  field :latitude, type: Float 
  field :longitude, type: Float
  field :coordinates, type: Array

  validates_presence_of :address, :city, :state, :allow_blank => false

  belongs_to :user

  validates_length_of :zip, :minimum => 5, :maximum => 5, :allow_blank => false


  # geocoded_by :full_address
  # after_validation :geocode

  # validates :address, :city, :state, :zip, presence: true



def full_address
    return "#{address}, #{city}, #{state}, #{zip}"
end
end

app/models/photo.rb
class Photo
    include Mongoid::Document
    include Mongoid::Paperclip

    field :date, type: DateTime

    belongs_to :user
    has_mongoid_attached_file :image, 
   		:styles => {
      :original => ['1920x1680>', :jpg],
      :small    => ['100x100#',   :jpg],
      :medium   => ['250x250',    :jpg],
      :large    => ['500x500>',   :jpg]
    }
    validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  has_secure_password

  validates_uniqueness_of :email
  
  field :username, type: String
  field :email, type: String
  field :password_digest, type: String
 
  has_many :photos
  has_many :events

  validates_length_of :email, :password_digest, :allow_blank => false

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

end

#Make authorize for user, edit similar to events

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :setup_user
  # before_action :authorize
  before_filter :authorize, :only => :edit

  helper_method :current_user
 

#memoization
  def current_user
  	@current_user ||= User.where(id: session[:user_id]).first
  end

  def setup_user
  	@user = User.new
  end

#Make two partials, one with the link, one without.

# if someone is logged in, use partial with links, else use partial without links.
def authorize
 redirect_to new_sessions_path if current_user.nil?
end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController	

	def index
		@events = Event.all
		
		@hash = Gmaps4rails.build_markers(@events) do |event, marker|
  			marker.lat event.to_coordinates.first
  			marker.lng event.to_coordinates.last
		end 

	end

	def show
		@event = Event.find(params[:id])	
			@hash = Gmaps4rails.build_markers(@event) do |event, marker|
  			marker.lat event.to_coordinates.first
  			marker.lng event.to_coordinates.last
		end

	end

	def new
		@event = Event.new
	end

	def create	
	    @event = Event.new(params.require(:event).permit(:full_address, :user_id, :date, :time, :title, :address, :city, :state, :zip, :desc, :latitude, :longitude))
	    @event.user_id = current_user.id.to_s

	 
		
	    if @event.save
	        redirect_to events_path
	     else
	   redirect_to new_event_path, notice: "Invalid, Check form and try again"
	    end
	end

	def edit
		@event = Event.find(params[:id])
	end

   def update  	
    @event = Event.find(params[:id])
	    if @event.update_attributes(params.require(:event).permit(:full_address, :title, :date, :time, :address, :city, :state, :zip, :desc, :latitude, :longitude))
	        redirect_to events_path
	     else
	        render 'edit'
	    end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path
	end

	
	
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end
  def new
    @photo =Photo.new
  end

  def show
	@photo = Photo.find(params[:id])
  end

  def create

    # Find our parent decision that we should attach to
    @photo = current_user.photos.new(photo_params)
    @photo.date ||= DateTime.now
    # Attach this criterion to a decision
    if @photo.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end
  
  def update
    @phto= Photo.find(params[:id])
    if @photo.update_attributes(params.require(:photo).permit(:image))
      redirect_to photos_path
    else
      render 'edit'
    end
  end
 

  def photo_params
    params.require(:photo).permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	# skip_before_action :authorize

	def new
		# Present an empty login form
		@user = User.new
		@is_login = true
	end

	def create
		# Find the user that is trying to log in		
		u = User.where(email: params[:user][:email]).first
		if u && u.authenticate(params[:user][:password])
			# Store as a cookie in the users' browser the ID of them,
			# indicating that they are logged in
			session[:user_id] = u.id.to_s
			redirect_to events_path
		else
			# Go back to the login page
			redirect_to new_sessions_path
		end
	end

	def destroy
		reset_session
		redirect_to events_path
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  

  # skip_before_action :authorize
    
# Lists all users, assigns to instance variable @users
  def index
    @users = User.all
  end

#Shows a user based on ID
  def show
      @user = User.find(params[:id])  
  end

# renders new blank user form, assigns to instance variable @user
  def new
    @user = User.new
  end

#actually creates new user, requires a user and allows the user fields
#in order to have a user, I have to have a user, and it can have these fields
  def create
    
    @user = User.new(params.require(:user).permit(:username, :email, :password, :password_confirmation))
    if @user.save  
      session[:user_id] = @user.id.to_s
          redirect_to @user, notice: 'User was successfully created.'
    else
      redirect_to new_user_path, notice: "Invalid, Check form and try again"
    end
  end

#renders edit page with correct user and form
  def edit
    @user = User.find(params[:id])
  end

#updates said user with username, email
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params.require(:user).permit(:username, :email))
      redirect_to users_path
    else
      render 'edit'
    end
  end

#finds user based on id, and deletes them
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  

  

  # def delete_post
  #   @user = User.find(params[:id])
  #   @post = @user.post
  #   @post.destroy
  #   redirect_to user_path
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">

      <div class="page-header">
        <h1>Edit Event</h1>
      </div>

      <%= form_for @event, :html => { :class => 'form-vertical' } do |f| %> 
        Title: <%= f.text_field :title, :class => 'form-control' %><br />   
        Date: <%= f.text_field :date, :data => {:provide => 'datepicker'}, :class => 'form-control'%><br />
        Time: <%= f.text_field :time, :class => 'form-control'%><br />
        Address: <%= f.text_field :address, :class => 'form-control' %><br /> 
        City: <%= f.text_field :city, :class => 'form-control' %><br />   
        State: <%= f.text_field :state, :class => 'form-control' %><br />
        Zipcode: <%= f.text_field :zip, :class => 'form-control' %><br />  
        Description: <%= f.text_area :desc, :class => 'form-control' %><br />
  
        <div class="form-actions">
          <%= f.submit nil, :class => 'btn btn-primary' %>
          <%= link_to t('.cancel', :default => t("helpers.links.cancel")), events_path, :class => 'btn' %>
        </div>
      <% end %>
      
    </div>

    <div class="page-header">
      <h1>Map</h1>
    </div>

    <div class="col-md-9">
      <%= render 'layouts/map' %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div id="map" style='width: 100%; height: 400px;'></div>

<div class="container-fluid">
  <div class="row">
   
    <div class="col-md-1"></div>
  <div class="col-md-10">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Date</th>
      <th>Address</th>
     
      <th>Desc</th>
      <th>Photos</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.title , event_path(event), :class => 'btn btn-mini' %></td>
        <td> <%= event.user.username%> </td>
        <td><%= event.date %> at <%= event.time %> </td>
        <td><%= event.address %>, <%= event.city %> <%= event.state %> <%= event.zip %></td>
        <td width="25%"><%= event.desc %></td>
      
        <td>
          <%= link_to "Show",  event_path(event), :class => 'btn btn-mini' %>
          
         <% if current_user && current_user.id == event.user_id %>

          <%= link_to "Edit", edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
          event_path(event), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
          :class => 'btn btn-mini btn-danger' %>

          <% end %>
         
        </td>
      </tr>
    <% end %>

  </tbody>
</table>

<%= link_to "New", "/events/new", :class => 'btn btn-primary' %>
 </div>
  <div class="col-md-1"></div>
</div>

<script>

  var eventArray = <%=raw @events.to_json %> 
  var markerArray = <%=raw @hash.to_json %>

 
     for(var i = 0; i<markerArray.length; i++){
        var theLink = eventArray[i]._id.$oid  

        markerArray[i].infowindow  =    "<div style='font-size: 14px'><strong><a href=events/" + theLink + ">" + eventArray[i].title + "<br>" + "</a></strong>"+ eventArray[i].address + "<br>" + eventArray[i].city + "<br>" + eventArray[i].state + ", " + eventArray[i].zip + "<br><br>" + "<div style='width:180px'><strong>Event Description:</strong> " + "<br>" + eventArray[i].desc; + "</div></div>"

      }

  handler = Gmaps.build('Google');
  var mapOptions = { mapTypeId: google.maps.MapTypeId.ROADMAP };
  handler.buildMap({ provider: mapOptions, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(markerArray);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
  });



  

</script>

app/views/events/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">

      <div class="page-header">
        <h1>New Event</h1>
      </div>
   <!-- invalid edit -->
    <% if flash[:notice] %>
      <div class="alert alert-danger"><%= flash[:notice] %></div>
    <% end %>

    <!-- successfull edit -->
    <% if flash[:alert] %>
      <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <%= flash[:alert] %>
      </div>
    <% end %>
      <%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %> 
        Title: <%= f.text_field :title, :class => 'form-control' %><br />   
        Date: <%= f.text_field :date, :data => {:provide => 'datepicker'}, :class => 'form-control'%><br />
        Time: <%= f.text_field :time, :class => 'form-control'%><br />
        Address: <%= f.text_field :address, :class => 'form-control' %><br /> 
        City: <%= f.text_field :city, :class => 'form-control' %><br />   
        State: <%= f.text_field :state, :class => 'form-control' %><br />
        Zipcode: <%= f.number_field :zip, :class => 'form-control' %><br />  
        Description: <%= f.text_area :desc, :class => 'form-control' %><br />
  
        <div class="form-actions">
          <%= f.submit nil, :class => 'btn btn-primary' %>
          <%= link_to "Cancel", events_path, :class => 'btn' %>

         
        </div>
      <% end %>
      
    </div>

    <div class="page-header">
      <h1>Map</h1>
    </div>

    <div class="col-md-9">
      <%= render 'layouts/map' %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container-fluid">
  <div class="row">
   
    <div class="col-md-2"></div>
    <div class="col-md-4">
     <div class="jumbotron">
      <h1>Event</h1>
     
<ul class="list-group">
  <li class="list-group-item">Event Creator: <%= @event.user.username%></li>
  <li class="list-group-item">Title: <%= @event.title%></li>
  <li class="list-group-item">Date: <%= @event.date%></li>
  <li class="list-group-item">Time: <%= @event.time%></li>
  <li class="list-group-item">Address: <%= @event.address %></li>
  <li class="list-group-item">City: <%= @event.city %></li>
  <li class="list-group-item">State: <%= @event.state %></li>
  <li class="list-group-item">Zip: <%= @event.zip %></li>
  <li class="list-group-item">Description: <%= @event.desc %></li>
  <li class="list-group-item">Coordinates: <%= @event.to_coordinates %></li>
 </ul>     


      <div class="form-actions">
        <%= link_to 'Back', events_path %>
        <% if current_user %>
          <%= link_to 'Edit', edit_event_path(@event), :class => 'btn' %> |
          <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }%>
        <% end %>
      </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="jumbotron">
      <h1>Event Map</h1>
      <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js">
      </script>
      <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
      <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
      <div id="map" style='width: 100%; height: 400px;'>
      </div>
      <script>

      // What does this do? -Mer COMMENT THE CODE
        var markerArray = <%=raw @hash.to_json %>;
        handler = Gmaps.build('Google');
        var mapOptions = { mapTypeId: google.maps.MapTypeId.hybrid, zoom: 8 };
        handler.buildMap({ provider: mapOptions, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(markerArray);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        //This is how to set the zoom, specifically after fitMapToBounds.
        handler.getMap().setZoom(12);
        });
      </script>
    </div>
  </div>
  <div class="col-md-2">   
  </div>
</div>

app/views/layouts/_login.html.erb
<%= form_for(@user, {url: sessions_path}) do |f| %>
    E-Mail: <%= f.text_field :email %>
    Password: <%= f.password_field :password %><%= f.submit "Login" %>
<% end %>

app/views/layouts/_map.html.erb
<head>
  <style type="text/css">
    html, body, #map-canvas { height: 100%; margin: 0; padding: 0;}
  </style>

<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDdVVw_ry9ZjBdAupGsrSzx6Pu4hBSZ7To">
    </script>
 
    <script type="text/javascript">


    function initialize() {

      var locations = [
         
               
    

      ];

      var myLatlng = new google.maps.LatLng(34.012982,-118.495186);

      var mapOptions = {
        center: myLatlng,
        zoom: 6
      };
      var map = new google.maps.Map(document.getElementById('map-canvas'),
          mapOptions);

      for (var i=0; i<locations.length; i++) {

        var marker = new google.maps.Marker({
          position: new google.maps.LatLng(locations[i].lat,locations[i].lng),
          map: map,
          title: locations[i].title
        });

      }


    }
    google.maps.event.addDomListener(window, 'load', initialize);
  </script>
</head>
<body>
<div id="map-canvas" style="width:100%; height:500px;"></div>
</body>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Event Mapper</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
       
        <li><%= link_to "Events", "/events"  %></li>
        <li><%= link_to "Users", "/users"  %></li>
        <% else %>
         <li><%= link_to "Events", "/events"  %></li>
        <% end %> 
      </ul>
  
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">User Options <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">    
              <li><%= link_to "Add Event", "/events/new"  %></li>
              
             
          </ul>
          </li>
         
          <li><a href="#"><%= current_user.email %></a></li>
          <li><%= link_to "Sign out", sessions_path, method: :delete %></li>
          <% else %>

         <li>  <div class="marginRight"><%= button_to "Sign Up", new_user_path, method: :get, :class => 'btn btn-default navbar-btn btn-sm' %></div></li>
         <li><div class="marginRight"><%= button_to "Sign In", new_sessions_path, method: :get, :class => 'btn btn-default navbar-btn btn-sm' %></div></li>

        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>EventsApp</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application'%>
	  <%= csrf_meta_tags %>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
	</head>
	<body>
	 	<%= render 'layouts/nav' %>
   		<%= yield %>
   	</body>
</html>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-1"></div>
   <div class="col-md-10">
<%= form_for @photo do |f| %>
	<%= f.file_field :image %>
	<%= f.submit %>
<% end %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
 </div>
  <div class="col-md-1"></div>
</div>

app/views/photos/new.html.erb
<h1>Add Profile Photo</h1>

<%= form_for @photo do |f| %>
	<%= f.file_field :image %>
	<%= f.submit %>
<% end %>

app/views/photos/show.html.erb
          <% @user.photos.each do |p| %>
        <%= image_tag p.image.url(:small), :class => "img-thumbnail picture hidden-xs" %>
      <% end %>
     

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-1"></div>
   <div class="col-md-10">
  <h1>Editing user</h1>
  <%= form_for(@user) do |f| %>
    E-mail: <%= f.text_field :email %>
    Password: <%= f.password_field :password %>
    Password Confirmation: <%= f.password_field :password_confirmation %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
 </div>
  <div class="col-md-1"></div>
</div>

app/views/users/index.html.erb
<div class="container-fluid">
  <div class="row">
   
  <div class="col-md-1"></div>
  <div class="col-md-10">
<h1>Listing users</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
 </div>
  <div class="col-md-1"></div>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="row">
   
  <div class="col-md-1"></div>
  <div class="col-md-10">

<% if flash[:notice] %>
	<div class="alert alert-danger"><%= flash[:notice] %></div>
	<% end %>
<br /><br />

  
<div class="col-sm-6 col-md-4 col-md-offset-4">
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong> <h2>Sign in to continue</h2></strong>
		</div>
		<div class="panel-body">
				<%= form_for @user, :html => { :class => 'form-vertical' }  do |f| %>
				<fieldset>
					<div class="row">
						<div class="center-block">
							<img class="profile-img"
								src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120" alt="">
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12 col-md-10  col-md-offset-1 ">
							<div class="form-group">
								<div class="input-group">
									<span class="input-group-addon">
										<i class="glyphicon glyphicon-user"></i>
									</span> 
									<%= f.text_field :username, placeholder: "Username", :class => 'form-control' %>
									
								</div>
							</div>
							<div class="form-group">
								<div class="input-group">
									<span class="input-group-addon">
										<i class="glyphicon glyphicon-lock"></i>
									</span>
									<%= f.text_field :email,  placeholder: "Email", :class => 'form-control' %>
								
								</div>
							</div>
							<div class="form-group">
								<div class="input-group">
									<span class="input-group-addon">
										<i class="glyphicon glyphicon-lock"></i>
									</span>
									<%= f.password_field :password,  placeholder: "Password", :class => 'form-control' %>
								
								</div>
							</div>
							<div class="form-group">
								<div class="input-group">
									<span class="input-group-addon">
										<i class="glyphicon glyphicon-lock"></i>
									</span>
									<%= f.password_field :password_confirmation,  placeholder: "Password Confirmation", :class => 'form-control' %>
								
								</div>
							</div>
							<div class="form-group">
								<%= f.submit "Sign Up", :class => 'bbtn btn-lg btn-primary btn-block' %>
								<% end %>
							</div>
						</div>
					</div>
				</fieldset>
			</form>
		</div>
		<div class="panel-footer ">
			Don't have an account! <a href="#" onClick=""> Sign Up Here </a><br />
			<%= link_to 'Back', users_path %>
		</div>
    </div>
</div>
	





		

		
	 </div>
  <div class="col-md-1"></div>
</div>

app/views/users/show.html.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container" style="margin-top: 20px; margin-bottom: 20px;">
	<div class="row panel">
		<div class="col-md-4 bg_blur ">
    	    <a href="#" class="follow_btn hidden-xs">Follow</a>
		</div>
    
        <div class="col-md-8  col-xs-12">
          <% @user.photos.each do |p| %>
            <%= image_tag p.image.url(:small), :class => "img-thumbnail picture hidden-xs" %>
          <% end %>
           <img src="http://lorempixel.com/output/people-q-c-100-100-1.jpg" class="img-thumbnail visible-xs picture_mob" />
           <div class="header">
                <h1> <%= @user.username %></h1>
                <h4> <%= @user.email %></h4>
                <span><%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Add Photo', new_photo_path %></span>
           </div>
        </div>
    </div>   
    
	<div class="row nav">    
        <div class="col-md-4"></div>
        <div class="col-md-8 col-xs-12" style="margin: 0px;padding: 0px;">
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-weixin fa-lg"></i> 16</div>
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-heart-o fa-lg"></i> 14</div>
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-thumbs-o-up fa-lg"></i> 26</div>
        </div>
    </div>
</div>
  <div class="row nav">    
        <div class="col-md-1"></div>
        <div class="col-md-10">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Time</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Desc</th>
      
    </tr>
  </thead>
<tbody>
	<% @user.events.each do |u| %>
	<tr>
		<td><%= u.title %></td>
		<td><%= u.date %></td>
		<td><%= u.time %></td>
		<td><%= u.address %></td>
		<td><%= u.city %></td>
		<td><%= u.state %></td>
		<td><%= u.zip %></td>
		<td><%= u.desc %></td>
	</tr>
	<% end %>
</tbody>
</table>
</div>
<div class="col-md-1"></div>